# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: php-zendserver:9.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - composer --version
          - phpunit --version
          - composer self-update
          - composer install --prefer-source --no-interaction --dev
          - phpunit